spring.application.name=user-service

server.port=9092

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness-user-db
spring.datasource.username=salman
spring.datasource.password=2580

# Auto create/update table
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
